# Generated by Django 3.2.8 on 2022-09-19 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appxa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='suject',
            new_name='subject',
        ),
    ]
